### ISSUE TITLE
Add an "open Commafeed on a new tab" button to the popup

### ISSUE THREAD

**Issue by antivirtel** [Athou/commafeed-browser-extension#1]
Hi,

Thanks for rewriting the code for this, I really missed the browser extension.

I see we have multiple ways of using it in the extension options, I have the default "Show CommaFeed in a popup" set (I'm in Chrome).
Can't we "combine them"? If I open the popup, I can't see a button to open Commafeed itself in a new tab.

Let's say I'm just taking a quick look, which is the popup great for, but if I want to go for it longer and read more, I'd love to have it open in a new tab (or at least resize the popup, but it isn't allowed either). Just another button here:
<img width="501" alt="Screenshot" src="https://github.com/Athou/commafeed-browser-extension/assets/3451979/9b1db11b-e6f0-402e-adff-964bbc38a1b4">
If you're there, maybe a button to open the extension's options too?

_BTW, is it possible to label the buttons there, so if I hover them it tells me what they mean? Eg. for the first the "Refresh" text would come up..._

_Also is there a dark mode planned for the extension and/or the webapp itself? I see the webapp can take custom CSS, but something out of the box?_

Thank you!

**Comment by Athou** [comment]
> I see we have multiple ways of using it in the extension options, I have the default "Show CommaFeed in a popup" set (I'm in Chrome). Can't we "combine them"? If I open the popup, I can't see a button to open Commafeed itself in a new tab.
> 
> Let's say I'm just taking a quick look, which is the popup great for, but if I want to go for it longer and read more, I'd love to have it open in a new tab (or at least resize the popup, but it isn't allowed either). Just another button here: <img alt="Screenshot" width="501" src="https://user-images.githubusercontent.com/3451979/243801056-9b1db11b-e6f0-402e-adff-964bbc38a1b4.png">
 If you're there, maybe a button to open the extension's options too?

That a great idea, I'll see what I can do.

> _BTW, is it possible to label the buttons there, so if I hover them it tells me what they mean? Eg. for the first the "Refresh" text would come up..._

Yes I can add something like this https://mantine.dev/core/tooltip/#close-and-open-delay

> _Also is there a dark mode planned for the extension and/or the webapp itself? I see the webapp can take custom CSS, but something out of the box?_

There should already be an entry in the profile menu :)
![image](https://github.com/Athou/commafeed-browser-extension/assets/1256795/5bdedf9a-9ba7-4dab-953f-9618ed810411)

**Comment by Athou** [comment]
Done! I'll deploy on commafeed.com once the Chrome team approves the new version of the extension on the store.

![image](https://github.com/Athou/commafeed-browser-extension/assets/1256795/e9aa37d8-37da-4961-ad2a-d20cd6596dc5)

**Comment by Athou** [comment]
The extension has been published and commafeed.com has been updated :)

**Comment by antivirtel** [comment]
Thank you very much for addressing all this, plus for this speed was amazing! 🍺

Re dark/light mode: Is there a way to get Commafeed and the extension to check what mode the OS/Browser is in currently, and follow that? Usually called follow system. I can raise a separate issue for that if you want.

**Comment by Athou** [comment]
> I can raise a separate issue for that if you want.

Yes, please :)
